version: '3.9'

services:
  logstash:
    container_name: logstash
    hostname: logstash
    build:
      context: ./logstash
    volumes:
      - ${PWD}/files/logstash/logstash.yml:/app/config/logstash.yml:ro
      - ${PWD}/files/logstash/pipelines.yml:/app/config/pipelines.yml:ro
      - ${PWD}/files/logstash/pipelines/ingest.conf:/app/config/pipelines/ingest.conf:ro
  logstash-oss:
    container_name: logstash-oss
    hostname: logstash-oss
    build:
      context: ./logstash
    volumes:
      - ${PWD}/files/logstash-oss/logstash.yml:/app/config/logstash.yml:ro
      - ${PWD}/files/logstash-oss/pipelines.yml:/app/config/pipelines.yml:ro
      - ${PWD}/files/logstash-oss/pipelines/ingest.conf:/app/config/pipelines/ingest.conf:ro
  filebeat:
    container_name: filebeat
    hostname: filebeat
    build:
      context: ./filebeat
    volumes:
      - ${PWD}/files/filebeat/filebeat.yml:/app/filebeat.yml:ro