version: '3.9'

services:
  nxlog-3-0-2272:
    container_name: nxlog-3-0-2272
    hostname: nxlog-3-0-2272
    build:
      args:
        - BASE_IMAGE=buster-slim
        - APP_VERSION=3.0.2272
      context: ./nxlog
    volumes:
      - ${PWD}/nxlog/files/nxlog.conf:/app/nxlog.conf:ro
      - ${PWD}/nxlog/files/server.log:/tmp/server.log:ro
      - certificates-data:/data:ro
  nxlog-2-9-1504:
    container_name: nxlog-2-9-1504
    hostname: nxlog-2-9-1504
    build:
      args:
        - BASE_IMAGE=jessie-slim
        - APP_VERSION=2.9.1504
      context: ./nxlog
    volumes:
      - ${PWD}/nxlog/files/nxlog.conf:/app/nxlog.conf:ro
      - ${PWD}/nxlog/files/server.log:/tmp/server.log:ro
      - certificates-data:/data:ro
  certificates:
    container_name: certificates
    hostname: certificates
    build:
      context: ./certificates
    volumes:
      - certificates-data:/app/data:rw
  logstash:
    container_name: logstash
    hostname: logstash
    build:
      context: ./logstash
    volumes:
      - ${PWD}/logstash/files/logstash.yml:/app/config/logstash.yml:ro
      - ${PWD}/logstash/files/pipelines.yml:/app/config/pipelines.yml:ro
      - ${PWD}/logstash/files/pipelines/ingest.conf:/app/config/pipelines/ingest.conf:ro
      - certificates-data:/data:ro
  logstash-oss:
    container_name: logstash-oss
    hostname: logstash-oss
    build:
      context: ./logstash-oss
    volumes:
      - ${PWD}/logstash-oss/files/logstash.yml:/app/config/logstash.yml:ro
      - ${PWD}/logstash-oss/files/pipelines.yml:/app/config/pipelines.yml:ro
      - ${PWD}/logstash-oss/files/pipelines/ingest.conf:/app/config/pipelines/ingest.conf:ro
      - certificates-data:/data:ro
#  filebeat:
#    container_name: filebeat
#    hostname: filebeat
#    build:
#      context: ./filebeat
#    volumes:
#      - ${PWD}/filebeat/filebeat.yml:/app/filebeat.yml:ro

volumes:
  certificates-data: